export {default as Home} from './Home.js'
export {default as Product} from './Product.js'
export {default as Genres} from './Genres.js'
export {default as Genre} from './Genre.js'
export {default as Cart} from './Cart.js'
export {default as Search} from './Search.js'
export {default as NotFound} from './NotFound.js'
export {default as Chekout} from './Chekout.js'